### ISSUE TITLE
Build project script is broken 

### ISSUE THREAD

**Issue by VSchuster** [LANDIS-II-Foundation/Library-Spatial#11]
Same issue that was a problem with core-model. [https://github.com/LANDIS-II-Foundation/Core-Model/issues/4](url) 
There are at least a couple of fixes that need to be considered now that this issue persists in more than one location:
1. Add the GDAL C# bindings into the `external\gdal\libs\managed\` directly. This is the same change that was done to core-model without knowledge that GDAL was being used in other locations.

2. Store the GDAL C# bindings to a google download and modify both scripts (and any other scripts that may have been affected by the code migration as they are found) to download the bindings into the appropriate location.

**Comment by rmscheller** [comment]
Vincent,

Your fixes seem reasonable; please proceed.  I assume you meant 'store the gdal c# bindings to a Github download... '

**Comment by rmscheller** [comment]
Resolved with new project files.  GDAL now delivered via .NET GDAL on Nuget
